// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA33_SxK90k37c3pSApNkGzSeGmnUjVZWk',
    appId: '1:465291344573:web:ceeb407b603e6e7b4f95d4',
    messagingSenderId: '465291344573',
    projectId: 'sidia-715d2',
    authDomain: 'sidia-715d2.firebaseapp.com',
    storageBucket: 'sidia-715d2.firebasestorage.app',
    measurementId: 'G-5L3LR9B913',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFq_Mj7Zxb0d4oXqMfswttc-7E_0tU3cI',
    appId: '1:465291344573:android:f9fb30f9909289684f95d4',
    messagingSenderId: '465291344573',
    projectId: 'sidia-715d2',
    storageBucket: 'sidia-715d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_-a6RYebQ0uTWRAViMtAE4T_CIercayQ',
    appId: '1:465291344573:ios:8049dcab3f74982b4f95d4',
    messagingSenderId: '465291344573',
    projectId: 'sidia-715d2',
    storageBucket: 'sidia-715d2.firebasestorage.app',
    iosBundleId: 'com.example.sidiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_-a6RYebQ0uTWRAViMtAE4T_CIercayQ',
    appId: '1:465291344573:ios:8049dcab3f74982b4f95d4',
    messagingSenderId: '465291344573',
    projectId: 'sidia-715d2',
    storageBucket: 'sidia-715d2.firebasestorage.app',
    iosBundleId: 'com.example.sidiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA33_SxK90k37c3pSApNkGzSeGmnUjVZWk',
    appId: '1:465291344573:web:cd70163292f1ee444f95d4',
    messagingSenderId: '465291344573',
    projectId: 'sidia-715d2',
    authDomain: 'sidia-715d2.firebaseapp.com',
    storageBucket: 'sidia-715d2.firebasestorage.app',
    measurementId: 'G-Y5ZJMNTZ2J',
  );
}
